url: "https://jeffdevine.com/"
title: "Jeff Devine" # the name of your site, e.g. ACME Corp.
description: "Jeff Devine is a musician, ex-whisky lover, and technologist living in New York City. He has 25 years of experience building technology and offers services as a fractional engineering leader."
tagelne: "Your Next Engineering Leader"

contact_form_api: 'https://ns2ncbequj.execute-api.us-east-1.amazonaws.com/contact'
exclude: [package.json, postcss.config.js, README.md, tailwind.config.js, yarn.lock]
permalink: /:categories/:title:output_ext
plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
postcss:
  cache: false
timezone: America/New_York

author:
  name     : "Jeff Devine"
  picture  : "/assets/images/jeff_devine_head_shot.png"
  bio      : "New York-based musician, wine snob, coffee appreciator, amateur sartorialist, and family man."
  bio_link : "/about.html"
  location : "Long Island City, NY"
  title    : "Fractional CTO"
  url      : https://jeffdevine.com

twitter:
  username: jeff_devine
  card: summary

social:
  name: Jeff Devine
  links:
    - https://www.linkedin.com/in/jeffdevine/
    - http://instagram.com/jive_ass_turkey_/
    - https://twitter.com/jeff_devine
    - https://github.com/jeffdevine
    - https://ruby.social/@jeff
