url: "https://jeffdevine.com"
title: "Jeff Devine" # the name of your site, e.g. ACME Corp.
description: "Jeff Devine is a musician, ex-whisky lover, and technologist living in New York City. He has 20+ years of experience building technology."
tagelne: "Your Next Engineering Leader"

exclude: [package.json, postcss.config.js, README.md, tailwind.config.js, yarn.lock]
permalink: /blog/:categories/:title:output_ext
plugins:
  - jekyll-minifier
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
jekyll-minifier:
  uglifier_args:
    harmony: true
  compress_css: false
  compress_javascript: true
postcss:
  cache: false
timezone: America/New_York

author:
  name     : "Jeff Devine"
  picture  : "/assets/images/jeff_devine_head_shot.png"
  bio      : "New York-based musician, wine snob, coffee appreciator, amateur sartorialist, and family man."
  location : "Long Island City, NY"
  url      : https://jeffdevine.com

twitter:
  username: jeff_devine
  card: summary

social:
  name: Jeff Devine
  links:
    - https://www.linkedin.com/in/jeffdevine/
    - http://instagram.com/jive_ass_turkey_/
    - https://twitter.com/jeff_devine
    - https://github.com/jeffdevine
    - https://ruby.social/@jeff
